### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by N9199** [ignaciohermosillacornejo/apuntes_icpc#2]
Añadir las siguientes cosas al repo:
- [ ] estructuras/avlTree (@ignaciohermosillacornejo )
- [ ] estructuras/treap (@ignaciohermosillacornejo )
- [x] graphs/floydWarshall (@ignaciohermosillacornejo )
- [ ] graphs/heavyLight
- [ ] graphs/prim (@jereyes4 )
- [ ] math/fastFourierTransform
- [ ] math/greenTheorem (@N9199 )
- [x] math/polynomials (@N9199 )
- [x] math/primalityChecks (@N9199 )
- [x] strings/suffixArray (@ignaciohermosillacornejo )
- [x] strings/KMP (@ignaciohermosillacornejo )
- [x] geometry/vectors2D (@N9199 )
- [ ] geometry/convexHull (@N9199 )
